// Code generated by "stringer -type=ExitCode -trimprefix=ExitCode -output=exitcode_string.go"; DO NOT EDIT.

package burnmint

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExitCodePendingBurnAlreadyExists-41200]
	_ = x[ExitCodePendingBurnNotFound-41201]
	_ = x[ExitCodePendingMintAlreadyExists-41202]
	_ = x[ExitCodePendingMintNotFound-41203]
	_ = x[ExitCodeUnexpectedBurnConfirmationSender-41204]
	_ = x[ExitCodeUnexpectedMintConfirmationSender-41205]
}

const _ExitCode_name = "PendingBurnAlreadyExistsPendingBurnNotFoundPendingMintAlreadyExistsPendingMintNotFoundUnexpectedBurnConfirmationSenderUnexpectedMintConfirmationSender"

var _ExitCode_index = [...]uint8{0, 24, 43, 67, 86, 118, 150}

func (i ExitCode) String() string {
	idx := int(i) - 41200
	if i < 41200 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
