// Code generated by "stringer -type=ExitCode -trimprefix=ExitCode -output=exitcode_string.go"; DO NOT EDIT.

package burnmint

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExitCodeUnexpectedBurnBounce-9400]
	_ = x[ExitCodeUnexpectedMintBounce-9401]
	_ = x[ExitCodeInvalidOffRampAccountReply-9402]
	_ = x[ExitCodeInvalidOffRampAccountNotification-9403]
	_ = x[ExitCodeOffRampAccountDeployFailed-9404]
}

const _ExitCode_name = "UnexpectedBurnBounceUnexpectedMintBounceInvalidOffRampAccountReplyInvalidOffRampAccountNotificationOffRampAccountDeployFailed"

var _ExitCode_index = [...]uint8{0, 20, 40, 66, 99, 125}

func (i ExitCode) String() string {
	idx := int(i) - 9400
	if i < 9400 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
