// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package offramp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorMessageNotFromOwnedContract-8400]
	_ = x[ErrorSourceChainNotEnabled-8401]
	_ = x[ErrorEmptyExecutionReport-8402]
	_ = x[ErrorInvalidMessageDestChainSelector-8403]
	_ = x[ErrorSourceChainSelectorMismatch-8404]
	_ = x[ErrorInvalidOnRampUpdate-8405]
	_ = x[ErrorSenderIsNotRouter-8406]
	_ = x[ErrorSubjectCursed-8407]
	_ = x[ErrorUnauthorized-8408]
	_ = x[ErrorZeroAddressNotAllowed-8409]
	_ = x[ErrorSignatureVerificationRequiredInCommitPlugin-8410]
	_ = x[ErrorSignatureVerificationNotAllowedInExecutionPlugin-8411]
	_ = x[ErrorInvalidInterval-8412]
	_ = x[ErrorBatchingNotSupported-8413]
}

const _ExitCode_name = "ErrorMessageNotFromOwnedContractErrorSourceChainNotEnabledErrorEmptyExecutionReportErrorInvalidMessageDestChainSelectorErrorSourceChainSelectorMismatchErrorInvalidOnRampUpdateErrorSenderIsNotRouterErrorSubjectCursedErrorUnauthorizedErrorZeroAddressNotAllowedErrorSignatureVerificationRequiredInCommitPluginErrorSignatureVerificationNotAllowedInExecutionPluginErrorInvalidIntervalErrorBatchingNotSupported"

var _ExitCode_index = [...]uint16{0, 32, 58, 83, 119, 151, 175, 197, 215, 232, 258, 306, 359, 379, 404}

func (i ExitCode) String() string {
	idx := int(i) - 8400
	if i < 8400 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
