// Code generated by "stringer -type=ExitCode -trimprefix=ExitCode -output=exitcode_string.go"; DO NOT EDIT.

package deposit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExitCodeOnlyOwner-8000]
	_ = x[ExitCodeOnlyBeneficiary-8001]
	_ = x[ExitCodeOnlySendExcessesToSender-8002]
}

const _ExitCode_name = "OnlyOwnerOnlyBeneficiaryOnlySendExcessesToSender"

var _ExitCode_index = [...]uint8{0, 9, 24, 48}

func (i ExitCode) String() string {
	idx := int(i) - 8000
	if i < 8000 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
