// Code generated by "enumer -type=FundMode -json -text -trimprefix=FundMode"; DO NOT EDIT.

package ton

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _FundModeName = "ExactAmountTopUp"

var _FundModeIndex = [...]uint8{0, 11, 16}

const _FundModeLowerName = "exactamounttopup"

func (i FundMode) String() string {
	if i >= FundMode(len(_FundModeIndex)-1) {
		return fmt.Sprintf("FundMode(%d)", i)
	}
	return _FundModeName[_FundModeIndex[i]:_FundModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FundModeNoOp() {
	var x [1]struct{}
	_ = x[FundModeExactAmount-(0)]
	_ = x[FundModeTopUp-(1)]
}

var _FundModeValues = []FundMode{FundModeExactAmount, FundModeTopUp}

var _FundModeNameToValueMap = map[string]FundMode{
	_FundModeName[0:11]:       FundModeExactAmount,
	_FundModeLowerName[0:11]:  FundModeExactAmount,
	_FundModeName[11:16]:      FundModeTopUp,
	_FundModeLowerName[11:16]: FundModeTopUp,
}

var _FundModeNames = []string{
	_FundModeName[0:11],
	_FundModeName[11:16],
}

// FundModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FundModeString(s string) (FundMode, error) {
	if val, ok := _FundModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FundModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FundMode values", s)
}

// FundModeValues returns all values of the enum
func FundModeValues() []FundMode {
	return _FundModeValues
}

// FundModeStrings returns a slice of all String values of the enum
func FundModeStrings() []string {
	strs := make([]string, len(_FundModeNames))
	copy(strs, _FundModeNames)
	return strs
}

// IsAFundMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FundMode) IsAFundMode() bool {
	for _, v := range _FundModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FundMode
func (i FundMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FundMode
func (i *FundMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FundMode should be a string, got %s", data)
	}

	var err error
	*i, err = FundModeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for FundMode
func (i FundMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for FundMode
func (i *FundMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = FundModeString(string(text))
	return err
}
