// Code generated by "enumer -type=Target -json -text -trimprefix=FundMode"; DO NOT EDIT.

package ton

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TargetName = "TargetAllTargetCCIPTargetMCMS"

var _TargetIndex = [...]uint8{0, 9, 19, 29}

const _TargetLowerName = "targetalltargetcciptargetmcms"

func (i Target) String() string {
	if i >= Target(len(_TargetIndex)-1) {
		return fmt.Sprintf("Target(%d)", i)
	}
	return _TargetName[_TargetIndex[i]:_TargetIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TargetNoOp() {
	var x [1]struct{}
	_ = x[TargetAll-(0)]
	_ = x[TargetCCIP-(1)]
	_ = x[TargetMCMS-(2)]
}

var _TargetValues = []Target{TargetAll, TargetCCIP, TargetMCMS}

var _TargetNameToValueMap = map[string]Target{
	_TargetName[0:9]:        TargetAll,
	_TargetLowerName[0:9]:   TargetAll,
	_TargetName[9:19]:       TargetCCIP,
	_TargetLowerName[9:19]:  TargetCCIP,
	_TargetName[19:29]:      TargetMCMS,
	_TargetLowerName[19:29]: TargetMCMS,
}

var _TargetNames = []string{
	_TargetName[0:9],
	_TargetName[9:19],
	_TargetName[19:29],
}

// TargetString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TargetString(s string) (Target, error) {
	if val, ok := _TargetNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TargetNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Target values", s)
}

// TargetValues returns all values of the enum
func TargetValues() []Target {
	return _TargetValues
}

// TargetStrings returns a slice of all String values of the enum
func TargetStrings() []string {
	strs := make([]string, len(_TargetNames))
	copy(strs, _TargetNames)
	return strs
}

// IsATarget returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Target) IsATarget() bool {
	for _, v := range _TargetValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Target
func (i Target) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Target
func (i *Target) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Target should be a string, got %s", data)
	}

	var err error
	*i, err = TargetString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Target
func (i Target) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Target
func (i *Target) UnmarshalText(text []byte) error {
	var err error
	*i, err = TargetString(string(text))
	return err
}
