// Code generated by "enumer -type=TargetProtocol -json -text -trimprefix=TargetProtocol"; DO NOT EDIT.

package ton

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TargetProtocolName = "CCIPMCMS"

var _TargetProtocolIndex = [...]uint8{0, 4, 8}

const _TargetProtocolLowerName = "ccipmcms"

func (i TargetProtocol) String() string {
	if i >= TargetProtocol(len(_TargetProtocolIndex)-1) {
		return fmt.Sprintf("TargetProtocol(%d)", i)
	}
	return _TargetProtocolName[_TargetProtocolIndex[i]:_TargetProtocolIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TargetProtocolNoOp() {
	var x [1]struct{}
	_ = x[TargetProtocolCCIP-(0)]
	_ = x[TargetProtocolMCMS-(1)]
}

var _TargetProtocolValues = []TargetProtocol{TargetProtocolCCIP, TargetProtocolMCMS}

var _TargetProtocolNameToValueMap = map[string]TargetProtocol{
	_TargetProtocolName[0:4]:      TargetProtocolCCIP,
	_TargetProtocolLowerName[0:4]: TargetProtocolCCIP,
	_TargetProtocolName[4:8]:      TargetProtocolMCMS,
	_TargetProtocolLowerName[4:8]: TargetProtocolMCMS,
}

var _TargetProtocolNames = []string{
	_TargetProtocolName[0:4],
	_TargetProtocolName[4:8],
}

// TargetProtocolString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TargetProtocolString(s string) (TargetProtocol, error) {
	if val, ok := _TargetProtocolNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TargetProtocolNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TargetProtocol values", s)
}

// TargetProtocolValues returns all values of the enum
func TargetProtocolValues() []TargetProtocol {
	return _TargetProtocolValues
}

// TargetProtocolStrings returns a slice of all String values of the enum
func TargetProtocolStrings() []string {
	strs := make([]string, len(_TargetProtocolNames))
	copy(strs, _TargetProtocolNames)
	return strs
}

// IsATargetProtocol returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TargetProtocol) IsATargetProtocol() bool {
	for _, v := range _TargetProtocolValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TargetProtocol
func (i TargetProtocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TargetProtocol
func (i *TargetProtocol) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TargetProtocol should be a string, got %s", data)
	}

	var err error
	*i, err = TargetProtocolString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for TargetProtocol
func (i TargetProtocol) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TargetProtocol
func (i *TargetProtocol) UnmarshalText(text []byte) error {
	var err error
	*i, err = TargetProtocolString(string(text))
	return err
}
