// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package rbac

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorUnauthorizedAccount-60900]
	_ = x[ErrorBadConfirmation-60901]
}

const _ExitCode_name = "ErrorUnauthorizedAccountErrorBadConfirmation"

var _ExitCode_index = [...]uint8{0, 24, 44}

func (i ExitCode) String() string {
	idx := int(i) - 60900
	if i < 60900 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
