// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package tvm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExitCodeSuccess-0]
	_ = x[ExitCodeSuccessVariant-1]
	_ = x[ExitCodeStackUnderflow-2]
	_ = x[ExitCodeStackOverflow-3]
	_ = x[ExitCodeIntegerOverflow-4]
	_ = x[ExitCodeIntegerOutOfExpectedRange-5]
	_ = x[ExitCodeInvalidOpcode-6]
	_ = x[ExitCodeTypeCheckError-7]
	_ = x[ExitCodeCellOverflow-8]
	_ = x[ExitCodeCellUnderflow-9]
	_ = x[ExitCodeDictionaryError-10]
	_ = x[ExitCodeUnknownError-11]
	_ = x[ExitCodeFatalError-12]
	_ = x[ExitCodeOutOfGasError-13]
	_ = x[ExitCodeOutOfGasErrorVariant - -14]
	_ = x[ExitCodeVirtualizationError-14]
	_ = x[ExitCodeActionListIsInvalid-32]
	_ = x[ExitCodeActionListIsTooLong-33]
	_ = x[ExitCodeActionIsInvalidOrNotSupported-34]
	_ = x[ExitCodeInvalidSourceAddressInOutboundMessage-35]
	_ = x[ExitCodeInvalidDestinationAddressInOutboundMessage-36]
	_ = x[ExitCodeNotEnoughToncoin-37]
	_ = x[ExitCodeNotEnoughExtraCurrencies-38]
	_ = x[ExitCodeOutboundMessageDoesNotFitIntoACellAfterRewriting-39]
	_ = x[ExitCodeCannotProcessAMessage-40]
	_ = x[ExitCodeLibraryReferenceIsNull-41]
	_ = x[ExitCodeLibraryChangeActionError-42]
	_ = x[ExitCodeExceededMaximumNumberOfCellsInTheLibraryOrTheMaximumDepthOfTheMerkleTree-43]
	_ = x[ExitCodeAccountStateSizeExceededLimits-50]
	_ = x[ExitCodeTolkUnmatchedOpcode-63]
	_ = x[ExitCodeNullReferenceException-128]
	_ = x[ExitCodeInvalidSerializationPrefix-129]
	_ = x[ExitCodeTactInvalidIncomingMessage-130]
	_ = x[ExitCodeTactConstraintsError-131]
	_ = x[ExitCodeTactAccessDenied-132]
	_ = x[ExitCodeTactContractStopped-133]
	_ = x[ExitCodeTactInvalidArgument-134]
	_ = x[ExitCodeTactCodeOfAContractWasNotFound-135]
	_ = x[ExitCodeTactInvalidStandardAddress-136]
	_ = x[ExitCodeTactNotABasechainAddress-138]
	_ = x[ExitCodeComputeSkipReasonNoState - -1]
	_ = x[ExitCodeComputeSkipReasonBadState - -2]
	_ = x[ExitCodeComputeSkipReasonNoGas - -3]
	_ = x[ExitCodeComputeSkipReasonSuspended - -4]
}

const (
	_ExitCode_name_0 = "ExitCodeOutOfGasErrorVariant"
	_ExitCode_name_1 = "ExitCodeComputeSkipReasonSuspendedExitCodeComputeSkipReasonNoGasExitCodeComputeSkipReasonBadStateExitCodeComputeSkipReasonNoStateExitCodeSuccessExitCodeSuccessVariantExitCodeStackUnderflowExitCodeStackOverflowExitCodeIntegerOverflowExitCodeIntegerOutOfExpectedRangeExitCodeInvalidOpcodeExitCodeTypeCheckErrorExitCodeCellOverflowExitCodeCellUnderflowExitCodeDictionaryErrorExitCodeUnknownErrorExitCodeFatalErrorExitCodeOutOfGasErrorExitCodeVirtualizationError"
	_ExitCode_name_2 = "ExitCodeActionListIsInvalidExitCodeActionListIsTooLongExitCodeActionIsInvalidOrNotSupportedExitCodeInvalidSourceAddressInOutboundMessageExitCodeInvalidDestinationAddressInOutboundMessageExitCodeNotEnoughToncoinExitCodeNotEnoughExtraCurrenciesExitCodeOutboundMessageDoesNotFitIntoACellAfterRewritingExitCodeCannotProcessAMessageExitCodeLibraryReferenceIsNullExitCodeLibraryChangeActionErrorExitCodeExceededMaximumNumberOfCellsInTheLibraryOrTheMaximumDepthOfTheMerkleTree"
	_ExitCode_name_3 = "ExitCodeAccountStateSizeExceededLimits"
	_ExitCode_name_4 = "ExitCodeTolkUnmatchedOpcode"
	_ExitCode_name_5 = "ExitCodeNullReferenceExceptionExitCodeInvalidSerializationPrefixExitCodeTactInvalidIncomingMessageExitCodeTactConstraintsErrorExitCodeTactAccessDeniedExitCodeTactContractStoppedExitCodeTactInvalidArgumentExitCodeTactCodeOfAContractWasNotFoundExitCodeTactInvalidStandardAddress"
	_ExitCode_name_6 = "ExitCodeTactNotABasechainAddress"
)

var (
	_ExitCode_index_1 = [...]uint16{0, 34, 64, 97, 129, 144, 166, 188, 209, 232, 265, 286, 308, 328, 349, 372, 392, 410, 431, 458}
	_ExitCode_index_2 = [...]uint16{0, 27, 54, 91, 136, 186, 210, 242, 298, 327, 357, 389, 469}
	_ExitCode_index_5 = [...]uint16{0, 30, 64, 98, 126, 150, 177, 204, 242, 276}
)

func (i ExitCode) String() string {
	switch {
	case i == -14:
		return _ExitCode_name_0
	case -4 <= i && i <= 14:
		i -= -4
		return _ExitCode_name_1[_ExitCode_index_1[i]:_ExitCode_index_1[i+1]]
	case 32 <= i && i <= 43:
		i -= 32
		return _ExitCode_name_2[_ExitCode_index_2[i]:_ExitCode_index_2[i+1]]
	case i == 50:
		return _ExitCode_name_3
	case i == 63:
		return _ExitCode_name_4
	case 128 <= i && i <= 136:
		i -= 128
		return _ExitCode_name_5[_ExitCode_index_5[i]:_ExitCode_index_5[i+1]]
	case i == 138:
		return _ExitCode_name_6
	default:
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
