// Code generated by "stringer -type=ExitCode -trimprefix=ExitCode -output=exitcode_string.go"; DO NOT EDIT.

package lockbox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenAmountCannotBeZero-56700]
	_ = x[RecipientCannotBeZeroAddress-56701]
	_ = x[UnsupportedToken-56702]
	_ = x[ContractAlreadyInitialized-56703]
	_ = x[ContractNotInitialized-56704]
}

const _ExitCode_name = "TokenAmountCannotBeZeroRecipientCannotBeZeroAddressUnsupportedTokenContractAlreadyInitializedContractNotInitialized"

var _ExitCode_index = [...]uint8{0, 23, 51, 67, 93, 115}

func (i ExitCode) String() string {
	idx := int(i) - 56700
	if i < 56700 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
