// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package feequoter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorUnsupportedChainFamilySelector-24800]
	_ = x[ErrorGasLimitTooHigh-24801]
	_ = x[ExtraArgOutOfOrderExecutionMustBeTrue-24802]
	_ = x[ErrorInvalidExtraArgsData-24803]
	_ = x[ErrorUnsupportedNumberOfTokens-24804]
	_ = x[ErrorInvalidSuiReceiverAddress-24805]
	_ = x[ErrorInvalidTokenReceiver-24806]
	_ = x[ErrorTooManySuiExtraArgsReceiverObjectIDs-24807]
	_ = x[ErrorMsgDataTooLarge-24808]
	_ = x[ErrorStaleGasPrice-24809]
	_ = x[ErrorDestChainNotEnabled-24810]
	_ = x[ErrorFeeTokenNotSupported-24811]
	_ = x[ErrorInvalidMsgData-24812]
	_ = x[ErrorTokenNotSupported-24813]
	_ = x[ErrorUnknownDestChainSelector-24814]
	_ = x[ErrorInsufficientFee-24815]
	_ = x[ErrorTokenTransfersNotSupported-24816]
	_ = x[ErrorUnauthorizedPriceUpdater-24817]
	_ = x[ErrorExecutionCostOverflow-24818]
	_ = x[ErrorPremiumFeeOverflow-24819]
	_ = x[ErrorDataAvailabilityCostOverflow-24820]
	_ = x[ErrorFeeCalculationOverflow-24821]
	_ = x[ErrorTokenPriceTooLow-24822]
	_ = x[ErrorFeeOverflow-24823]
	_ = x[ErrorMessageFeeTooHigh-24824]
}

const _ExitCode_name = "ErrorUnsupportedChainFamilySelectorErrorGasLimitTooHighExtraArgOutOfOrderExecutionMustBeTrueErrorInvalidExtraArgsDataErrorUnsupportedNumberOfTokensErrorInvalidSuiReceiverAddressErrorInvalidTokenReceiverErrorTooManySuiExtraArgsReceiverObjectIDsErrorMsgDataTooLargeErrorStaleGasPriceErrorDestChainNotEnabledErrorFeeTokenNotSupportedErrorInvalidMsgDataErrorTokenNotSupportedErrorUnknownDestChainSelectorErrorInsufficientFeeErrorTokenTransfersNotSupportedErrorUnauthorizedPriceUpdaterErrorExecutionCostOverflowErrorPremiumFeeOverflowErrorDataAvailabilityCostOverflowErrorFeeCalculationOverflowErrorTokenPriceTooLowErrorFeeOverflowErrorMessageFeeTooHigh"

var _ExitCode_index = [...]uint16{0, 35, 55, 92, 117, 147, 177, 202, 243, 263, 281, 305, 330, 349, 371, 400, 420, 451, 480, 506, 529, 562, 589, 610, 626, 648}

func (i ExitCode) String() string {
	idx := int(i) - 24800
	if i < 24800 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
