run:
  timeout: 60s

linters:
  verbose: true
  enable:
    - copyloopvar
    - depguard
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/smartcontractkit/chainlink-ton

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - revive
      text: "dot-imports"
