#!/usr/bin/env bash

# Generates go.md

set -e

# Unset GOROOT to avoid conflicts with locally installed Go versions
# This ensures we use the Go toolchain in PATH (e.g., from nix)
unset GOROOT

echo "# smartcontractkit Go modules
## Main module
\`\`\`mermaid
flowchart LR
"
go mod graph | go tool modgraph -prefix github.com/smartcontractkit/
echo "\`\`\`"

echo "## All modules
\`\`\`mermaid
flowchart LR
"
go tool gomods graph | go tool modgraph -prefix github.com/smartcontractkit/
echo "\`\`\`"