// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package jetton

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorInvalidOp-72]
	_ = x[ErrorWrongOp-65535]
	_ = x[ErrorNotOwner-73]
	_ = x[ErrorNotValidWallet-74]
	_ = x[ErrorWrongWorkchain-333]
}

const (
	_ExitCode_name_0 = "ErrorInvalidOpErrorNotOwnerErrorNotValidWallet"
	_ExitCode_name_1 = "ErrorWrongWorkchain"
	_ExitCode_name_2 = "ErrorWrongOp"
)

var (
	_ExitCode_index_0 = [...]uint8{0, 14, 27, 46}
)

func (i ExitCode) String() string {
	switch {
	case 72 <= i && i <= 74:
		i -= 72
		return _ExitCode_name_0[_ExitCode_index_0[i]:_ExitCode_index_0[i+1]]
	case i == 333:
		return _ExitCode_name_1
	case i == 65535:
		return _ExitCode_name_2
	default:
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
