// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package offramp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorMessageNotFromOwnedContract-22100]
	_ = x[ErrorSourceChainNotEnabled-22101]
	_ = x[ErrorEmptyExecutionReport-22102]
	_ = x[ErrorInvalidMessageDestChainSelector-22103]
	_ = x[ErrorSourceChainSelectorMismatch-22104]
	_ = x[ErrorInvalidOnRampUpdate-22105]
	_ = x[ErrorInsufficientFee-22106]
	_ = x[ErrorSubjectCursed-22107]
	_ = x[ErrorUnauthorized-22108]
	_ = x[ErrorZeroAddressNotAllowed-22109]
	_ = x[ErrorTooManyMessagesInReport-22110]
	_ = x[ErrorSignatureVerificationRequiredInCommitPlugin-22111]
	_ = x[ErrorSignatureVerificationNotAllowedInExecutionPlugin-22112]
	_ = x[ErrorInvalidInterval-22113]
	_ = x[ErrorBatchingNotSupported-22114]
	_ = x[ErrorOnRampAddressMismatch-22115]
	_ = x[ErrorEmptyCommitReport-22116]
	_ = x[ErrorMerkleRootCannotBeZero-22117]
}

const _ExitCode_name = "ErrorMessageNotFromOwnedContractErrorSourceChainNotEnabledErrorEmptyExecutionReportErrorInvalidMessageDestChainSelectorErrorSourceChainSelectorMismatchErrorInvalidOnRampUpdateErrorInsufficientFeeErrorSubjectCursedErrorUnauthorizedErrorZeroAddressNotAllowedErrorTooManyMessagesInReportErrorSignatureVerificationRequiredInCommitPluginErrorSignatureVerificationNotAllowedInExecutionPluginErrorInvalidIntervalErrorBatchingNotSupportedErrorOnRampAddressMismatchErrorEmptyCommitReportErrorMerkleRootCannotBeZero"

var _ExitCode_index = [...]uint16{0, 32, 58, 83, 119, 151, 175, 195, 213, 230, 256, 284, 332, 385, 405, 430, 456, 478, 505}

func (i ExitCode) String() string {
	idx := int(i) - 22100
	if i < 22100 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
