// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package ocr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorBigFMustBePositive-3100]
	_ = x[ErrorStaticConfigCannotBeChanged-3101]
	_ = x[ErrorTooManySigners-3102]
	_ = x[ErrorBigFTooHigh-3103]
	_ = x[ErrorTooManyTransmitters-3104]
	_ = x[ErrorNoTransmitters-3105]
	_ = x[ErrorRepeatedSigners-3106]
	_ = x[ErrorRepeatedTransmitters-3107]
	_ = x[ErrorConfigDigestMismatch-3108]
	_ = x[ErrorUnauthorizedTransmitter-3109]
	_ = x[ErrorWrongNumberOfSignatures-3110]
	_ = x[ErrorUnauthorizedSigner-3111]
	_ = x[ErrorNonUniqueSignatures-3112]
	_ = x[ErrorInvalidSignature-3113]
	_ = x[ErrorNonExistentOcrPluginType-3114]
	_ = x[ErrorNoSigners-3115]
}

const _ExitCode_name = "ErrorBigFMustBePositiveErrorStaticConfigCannotBeChangedErrorTooManySignersErrorBigFTooHighErrorTooManyTransmittersErrorNoTransmittersErrorRepeatedSignersErrorRepeatedTransmittersErrorConfigDigestMismatchErrorUnauthorizedTransmitterErrorWrongNumberOfSignaturesErrorUnauthorizedSignerErrorNonUniqueSignaturesErrorInvalidSignatureErrorNonExistentOcrPluginTypeErrorNoSigners"

var _ExitCode_index = [...]uint16{0, 23, 55, 74, 90, 114, 133, 153, 178, 203, 231, 259, 282, 306, 327, 356, 370}

func (i ExitCode) String() string {
	idx := int(i) - 3100
	if i < 3100 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
