[onchain]

[[onchain.ton_blockchain]]
chainID = -3
name = "my_local_ton"
httpURL = "liteserver://E7XwFSQzNkcRepUC23J2nRpASXpnsEKmyyHYV4u/FZY=@127.0.0.1:40004"
deployerKey = ""
walletVersion = "V5R1"

[[onchain.evm_blockchain]]
chainID = 11155111
name = "local_ethereum_sepolia"
httpURL = "http://127.0.0.1:8545"
wssURL = "wss://127.0.0.1:8545"
deployerKey = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
