// Package tvm is a temporary compatibility shim that re-exports the public
// API of github.com/smartcontractkit/chainlink-ton/cciplib/ton/tvm that is still used by
// this repo's dependent modules (deployment, devenv, integration-tests,
// staging-monitor) and by mcms v0.45.0.
//
// The real implementation lives in the standalone cciplib module. Symbols are
// re-exported as aliases (=) so their identity matches cciplib's exactly.
//
// Code generated by shimgen; DO NOT EDIT. DELETE this shim once all consumers
// import the cciplib path directly.
package tvm

import (
	context "context"

	address "github.com/xssnick/tonutils-go/address"
	ton "github.com/xssnick/tonutils-go/ton"

	src "github.com/smartcontractkit/chainlink-ton/cciplib/ton/tvm"
)

func CallGetter[A any, R any](ctx context.Context, client ton.APIClientWrapped, block *ton.BlockIDExt, contractAddr *address.Address, getter src.Getter[A, R], input ...A) (R, error) {
	return src.CallGetter[A, R](ctx, client, block, contractAddr, getter, input...)
}

func CallGetterLatest[A any, R any](ctx context.Context, client ton.APIClientWrapped, contractAddr *address.Address, getter src.Getter[A, R], input ...A) (R, error) {
	return src.CallGetterLatest[A, R](ctx, client, contractAddr, getter, input...)
}

type ContractTLBRegistry = src.ContractTLBRegistry

type Getter[A any, R any] = src.Getter[A, R]

var EmptyCell = src.EmptyCell

type ExitCode = src.ExitCode

const ExitCodeComputeSkipReasonNoState = src.ExitCodeComputeSkipReasonNoState

const ExitCodeSuccess = src.ExitCodeSuccess

const SizeUINT8 = src.SizeUINT8

const SizeUINT256 = src.SizeUINT256

var ExtractOpcode = src.ExtractOpcode

type FullyQualifiedName = src.FullyQualifiedName

var LinkTokenAddr = src.LinkTokenAddr

var MustNewTLBMap = src.MustNewTLBMap

var MyLocalTONWalletDefault = src.MyLocalTONWalletDefault

var NewInitializedWallet = src.NewInitializedWallet

var NewRandomHighloadV3TestWallet = src.NewRandomHighloadV3TestWallet

var NewRandomTestWallet = src.NewRandomTestWallet

var NewRandomV5R1TestWallet = src.NewRandomV5R1TestWallet

var NewV5R1Wallet = src.NewV5R1Wallet

var RandomQueryID = src.RandomQueryID

var TLBMapKeyStorage = src.TLBMapKeyStorage

var TonTokenAddr = src.TonTokenAddr

var ZeroAddress = src.ZeroAddress
