package tonutils

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/xssnick/tonutils-go/address"
	"github.com/xssnick/tonutils-go/tlb"
	"github.com/xssnick/tonutils-go/ton"
	"github.com/xssnick/tonutils-go/ton/wallet"
	"github.com/xssnick/tonutils-go/tvm/cell"
)

type ApiClient struct {
	Api    ton.APIClientWrapped
	Wallet wallet.Wallet
}

// SendWaitTransaction waits for the transaction to be sent and returns the
// resulting message with the outgoing messages if any.
func (ac *ApiClient) SendWaitTransaction(ctx context.Context, dstAddr address.Address, messageToSend *wallet.Message) (*ReceivedMessage, uint32, error) {
	tx, block, err := ac.Wallet.SendWaitTransaction(ctx, messageToSend)
	if err != nil {
		return nil, 0, fmt.Errorf("deposit transaction failed for %s: %w", dstAddr.String(), err)
	}

	receivedMessage, err := MapToReceivedMessage(tx)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to get outgoing messages: %w", err)
	}
	return &receivedMessage, block.SeqNo, nil
}

// WaitForTrace waits for all outgoing messages to be received and all their
// outgoing messages to be received recursively. It will return the resulting
// message in a Finalized state.
func (m *ReceivedMessage) WaitForTrace(ac *ApiClient) error {
	if m.Status() == Finalized {
		return nil
	}

	messagesWithUnconfirmedOutgoingMessages := NewEmptyQueue[*ReceivedMessage]()
	messagesWithUnconfirmedOutgoingMessages.Push(m)

	for {
		cascadingMessage, ok := messagesWithUnconfirmedOutgoingMessages.Pop()
		if !ok {
			break
		}
		err := cascadingMessage.WaitForOutgoingMessagesToBeReceived(ac)
		if err != nil {
			return fmt.Errorf("failed to wait for outgoing messages: %w", err)
		}
		messagesWithUnconfirmedOutgoingMessages.PushAll(cascadingMessage.OutgoingInternalMessagesReceived...)
	}
	return nil
}

// SendWaitTransactionRecursively waits for the transaction to be sent and
// waits for all outgoing messages to be confirmed recursively. It will return
// the resulting message in a Finalized state.
func (ac *ApiClient) SendWaitTransactionRecursively(ctx context.Context, dstAddr address.Address, messageToSend *wallet.Message) (*ReceivedMessage, error) {
	sentMessage, seqno, err := ac.SendWaitTransaction(ctx, dstAddr, messageToSend)
	if err != nil {
		return nil, fmt.Errorf("failed to SendWaitTransaction: %w", err)
	}
	err = sentMessage.WaitForTrace(ac)
	if err != nil {
		return nil, fmt.Errorf("failed to wait for trace: %w", err)
	}
	master, err := ac.Api.WaitForBlock(seqno).CurrentMasterchainInfo(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get masterchain info for funder balance check: %w", err)
	}
	fmt.Printf("Masterchain SeqNo: %d\n", master.SeqNo)

	for {
		// Check if the block is ready
		if master.SeqNo > seqno+1 {
			break
		}
		time.Sleep(time.Millisecond * 500)
		fmt.Printf("Waiting for block %d to be ready...\n", seqno)
		master, err = ac.Api.WaitForBlock(seqno).CurrentMasterchainInfo(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to get masterchain info for funder balance check: %w", err)
		}
		fmt.Printf("Masterchain SeqNo: %d\n", master.SeqNo)
	}

	return sentMessage, nil
}

// SubscribeToTransactions returns a channel with all incoming transactions for
// the given address that came after lt (Lamport Time). It will work
// retroactively, so it will return all transactions that are already in the
// blockchain and all new ones.
func (ac *ApiClient) SubscribeToTransactions(address address.Address, lt uint64) chan *tlb.Transaction {
	transactionsReceived := make(chan *tlb.Transaction)

	// it is a blocking call, so we start it asynchronously
	go ac.Api.SubscribeOnTransactions(context.Background(), &address, lt, transactionsReceived)
	return transactionsReceived
}

// SubscribeToMessages returns a channel with all incoming messages for the
// given address that came after lt (Lamport Time). It will work retroactively,
// meaning that it will return all messages that are already in the blockchain
// and all new ones.
func (ac *ApiClient) SubscribeToMessages(address address.Address, lt uint64) chan *ReceivedMessage {
	messagesReceived := make(chan *ReceivedMessage)
	go func() {
		transactionsReceived := ac.SubscribeToTransactions(address, lt)

		for rTX := range transactionsReceived {
			if rTX.IO.In != nil {
				var err error
				receivedMessage, err := MapToReceivedMessage(rTX)
				if err != nil {
				}
				messagesReceived <- &receivedMessage
			}
		}
	}()
	return messagesReceived
}

type CompiledContract struct {
	Name string `json:"name"`
	Code string `json:"code"`
	Abi  string `json:"abi"`
}

// Deploy deploys a contract to the blockchain. It takes the path to the
// .pkg artifact generated by the TON compiler and the initial data for the
// contract. It returns the address of the deployed contract. It will return an
// error if the deployment fails; exit code must be 130.
func (ac *ApiClient) Deploy(contractPath string, initData *cell.Cell) (*Contract, error) {
	compiledContract, err := getCompiledContract(contractPath)
	if err != nil {
		return nil, fmt.Errorf("Failed to compile contract: %v", err)
	}

	// Extract the Base64-encoded BOC
	codeBoc64 := compiledContract.Code
	if codeBoc64 == "" {
		return nil, fmt.Errorf("codeBoc64 field is empty in the JSON")
	}

	// Decode the Base64 string to get the actual BOC binary
	codeBocBinary, err := base64.StdEncoding.DecodeString(codeBoc64)
	if err != nil {
		return nil, fmt.Errorf("Failed to decode base64: %v", err)
	}

	// Parse the BOC binary into a cell
	codeCell, err := cell.FromBOC(codeBocBinary)
	if err != nil {
		return nil, fmt.Errorf("Failed to parse BOC binary: %v", err)
	}

	// Create empty message body for deployment
	msgBody := cell.BeginCell().EndCell()

	// Deploy the contract
	addr, tx, _, err := ac.Wallet.DeployContractWaitTransaction(
		context.Background(),
		tlb.MustFromTON("1"), // Amount to attach to deployment
		msgBody,
		codeCell,
		initData,
	)
	if err != nil {
		return nil, fmt.Errorf("deployment failed: %v", err)
	}

	receivedMessage, err := MapToReceivedMessage(tx)
	if err != nil {
		return nil, fmt.Errorf("failed to get outgoing messages: %w", err)
	}
	err = receivedMessage.WaitForTrace(ac)
	if err != nil {
		return nil, fmt.Errorf("failed to wait for trace: %w", err)
	}
	if receivedMessage.ExitCode != ExitCode_Success || len(receivedMessage.OutgoingInternalMessagesReceived) != 1 {
		return nil, fmt.Errorf("contract deployment failed: error sending external message: exit code %d: %s", receivedMessage.ExitCode, receivedMessage.ExitCode.Describe())

	}
	deployExitCode := receivedMessage.OutgoingInternalMessagesReceived[0].ExitCode
	if !deployExitCode.IsSuccessfulDeployment() {
		return nil, fmt.Errorf("contract deployment failed: exit code %d: %s", deployExitCode, deployExitCode.Describe())
	}

	return &Contract{addr, ac}, nil
}

func getCompiledContract(contractPath string) (CompiledContract, error) {
	// Check if contract file exists
	if _, err := os.Stat(contractPath); os.IsNotExist(err) {
		return CompiledContract{}, fmt.Errorf("Contract file not found: %s", contractPath)
	}
	jsonData, err := os.ReadFile(contractPath)
	if err != nil {
		return CompiledContract{}, fmt.Errorf("Failed to read compiled contract: %v", err)
	}

	// Parse the JSON
	var compiledContract CompiledContract
	err = json.Unmarshal(jsonData, &compiledContract)
	if err != nil {
		return CompiledContract{}, fmt.Errorf("Failed to parse JSON: %v", err)
	}
	return compiledContract, nil

}
