// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package merkleroot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorAlreadyExecuted-47900]
	_ = x[ErrorNotOwner-47901]
	_ = x[ErrorManualExecutionNotYetEnabled-47902]
	_ = x[ErrorSkippedAlreadyExecutedMessage-47903]
	_ = x[ErrorInvalidState-47904]
	_ = x[ErrorSeqNumOutOfBounds-47905]
}

const _ExitCode_name = "ErrorAlreadyExecutedErrorNotOwnerErrorManualExecutionNotYetEnabledErrorSkippedAlreadyExecutedMessageErrorInvalidStateErrorSeqNumOutOfBounds"

var _ExitCode_index = [...]uint8{0, 20, 33, 66, 100, 117, 139}

func (i ExitCode) String() string {
	idx := int(i) - 47900
	if i < 47900 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
