// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package merkleroot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorAlreadyExecuted-18600]
	_ = x[ErrorNotOwner-18601]
	_ = x[ErrorManualExecutionNotYetEnabled-18602]
	_ = x[ErrorSkippedAlreadyExecutedMessage-18603]
	_ = x[ErrorInvalidState-18604]
	_ = x[ErrorSeqNumOutOfBounds-18605]
}

const _ExitCode_name = "ErrorAlreadyExecutedErrorNotOwnerErrorManualExecutionNotYetEnabledErrorSkippedAlreadyExecutedMessageErrorInvalidStateErrorSeqNumOutOfBounds"

var _ExitCode_index = [...]uint8{0, 20, 33, 66, 100, 117, 139}

func (i ExitCode) String() string {
	idx := int(i) - 18600
	if i < 18600 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
