// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package merkleroot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorInvalidProofLeavesCannotBeEmpty-20400]
	_ = x[ErrorInvalidProofLeavesTooLarge-20401]
	_ = x[ErrorInvalidProofProofsTooLarge-20402]
	_ = x[ErrorInvalidProofTotalHashesExceededMax-20403]
}

const _ExitCode_name = "ErrorInvalidProofLeavesCannotBeEmptyErrorInvalidProofLeavesTooLargeErrorInvalidProofProofsTooLargeErrorInvalidProofTotalHashesExceededMax"

var _ExitCode_index = [...]uint8{0, 36, 67, 98, 137}

func (i ExitCode) String() string {
	idx := int(i) - 20400
	if i < 20400 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
