// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package ownable2step

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorOnlyCallableByOwner-132]
	_ = x[ErrorCannotTransferToSelf-1001]
	_ = x[ErrorMustBeProposedOwner-1002]
}

const (
	_ExitCode_name_0 = "ErrorOnlyCallableByOwner"
	_ExitCode_name_1 = "ErrorCannotTransferToSelfErrorMustBeProposedOwner"
)

var (
	_ExitCode_index_1 = [...]uint8{0, 25, 49}
)

func (i ExitCode) String() string {
	switch {
	case i == 132:
		return _ExitCode_name_0
	case 1001 <= i && i <= 1002:
		i -= 1001
		return _ExitCode_name_1[_ExitCode_index_1[i]:_ExitCode_index_1[i+1]]
	default:
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
