tolk 0.99

const OP_SCHEDULE = 0xc3e106f4; // "OP_SCHEDULE"c; // 0xc3e106f4
const OP_CANCEL = 0x70b511b7; // "OP_CANCEL"c; // 0x70b511b7
const OP_EXECUTE = 0x2f25a5fd; // "OP_EXECUTE"c; // 0x2f25a5fd
const OP_TOP_UP = 0x2a6fa953; // "OP_TOP_UP"c; // 0x2a6fa953
const OP_UPDATE_DELAY = 0x7be47a8e; // "OP_UPDATE_DELAY"c; // 0x7be47a8e
const OP_CLEAR_TIMESTAMPS = 0xe8448df0; // "OP_CLEAR_TIMESTAMPS"c; // 0xe8448df0
