// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package tokenpool

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorInvalidTransferFeeBps-51700]
	_ = x[ErrorInvalidTokenTransferFeeConfig-51701]
	_ = x[ErrorCallerIsNotARampOnRouter-51702]
	_ = x[ErrorZeroAddressInvalid-51703]
	_ = x[ErrorNonExistentChain-51704]
	_ = x[ErrorChainNotAllowed-51705]
	_ = x[ErrorCursedByRMN-51706]
	_ = x[ErrorChainAlreadyExists-51707]
	_ = x[ErrorInvalidSourcePoolAddress-51708]
	_ = x[ErrorInvalidToken-51709]
	_ = x[ErrorUnauthorized-51710]
	_ = x[ErrorPoolAlreadyAdded-51711]
	_ = x[ErrorInvalidRemotePoolForChain-51712]
	_ = x[ErrorInvalidRemoteChainDecimals-51713]
	_ = x[ErrorOverflowDetected-51714]
	_ = x[ErrorInvalidDecimalArgs-51715]
	_ = x[ErrorCallerIsNotOwnerOrFeeAdmin-51716]
	_ = x[ErrorUnsupportedOperation-51717]
	_ = x[ErrorMissingForwardPayload-51718]
	_ = x[ErrorMissingTransferInitiator-51719]
	_ = x[ErrorAmountMismatch-51720]
	_ = x[ErrorInvalidRequestedFinality-51721]
	_ = x[ErrorRateLimitExceeded-51722]
}

const _ExitCode_name = "ErrorInvalidTransferFeeBpsErrorInvalidTokenTransferFeeConfigErrorCallerIsNotARampOnRouterErrorZeroAddressInvalidErrorNonExistentChainErrorChainNotAllowedErrorCursedByRMNErrorChainAlreadyExistsErrorInvalidSourcePoolAddressErrorInvalidTokenErrorUnauthorizedErrorPoolAlreadyAddedErrorInvalidRemotePoolForChainErrorInvalidRemoteChainDecimalsErrorOverflowDetectedErrorInvalidDecimalArgsErrorCallerIsNotOwnerOrFeeAdminErrorUnsupportedOperationErrorMissingForwardPayloadErrorMissingTransferInitiatorErrorAmountMismatchErrorInvalidRequestedFinalityErrorRateLimitExceeded"

var _ExitCode_index = [...]uint16{0, 26, 60, 89, 112, 133, 153, 169, 192, 221, 238, 255, 276, 306, 337, 358, 381, 412, 437, 463, 492, 511, 540, 562}

func (i ExitCode) String() string {
	idx := int(i) - 51700
	if i < 51700 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
