// Code generated by "stringer -type=ExitCode -trimprefix=ExitCode -output=exitcode_string.go"; DO NOT EDIT.

package contextexecutor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExitCodeOnlyCallableByOwner-26000]
}

const _ExitCode_name = "OnlyCallableByOwner"

var _ExitCode_index = [...]uint8{0, 19}

func (i ExitCode) String() string {
	idx := int(i) - 26000
	if i < 26000 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
