// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package router

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorDestChainNotEnabled-57100]
	_ = x[ErrorSourceChainNotEnabled-57101]
	_ = x[SenderIsNotOffRamp-57102]
	_ = x[OffRampNotSetForSelector-57103]
	_ = x[OffRampAddressMismatch-57104]
	_ = x[ErrorSubjectCursed-57105]
	_ = x[ErrorNotOnRamp-57106]
	_ = x[ErrorMissingTokenAmounts-57107]
	_ = x[ErrorNoMultiTokenTransfers-57108]
	_ = x[ErrorInsufficientFee-57109]
}

const _ExitCode_name = "ErrorDestChainNotEnabledErrorSourceChainNotEnabledSenderIsNotOffRampOffRampNotSetForSelectorOffRampAddressMismatchErrorSubjectCursedErrorNotOnRampErrorMissingTokenAmountsErrorNoMultiTokenTransfersErrorInsufficientFee"

var _ExitCode_index = [...]uint8{0, 24, 50, 68, 92, 114, 132, 146, 170, 196, 216}

func (i ExitCode) String() string {
	idx := int(i) - 57100
	if i < 57100 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
