// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package router

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorDestChainNotEnabled-49600]
	_ = x[ErrorSourceChainNotEnabled-49601]
	_ = x[SenderIsNotOffRamp-49602]
	_ = x[OffRampNotSetForSelector-49603]
	_ = x[OffRampAddressMismatch-49604]
	_ = x[ErrorUnknownMessage-4098]
}

const (
	_ExitCode_name_0 = "ErrorUnknownMessage"
	_ExitCode_name_1 = "ErrorDestChainNotEnabledErrorSourceChainNotEnabledSenderIsNotOffRampOffRampNotSetForSelectorOffRampAddressMismatch"
)

var (
	_ExitCode_index_1 = [...]uint8{0, 24, 50, 68, 92, 114}
)

func (i ExitCode) String() string {
	switch {
	case i == 4098:
		return _ExitCode_name_0
	case 49600 <= i && i <= 49604:
		i -= 49600
		return _ExitCode_name_1[_ExitCode_index_1[i]:_ExitCode_index_1[i+1]]
	default:
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
