// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package router

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorDestChainNotEnabled-49600]
	_ = x[ErrorSourceChainNotEnabled-49601]
	_ = x[SenderIsNotOffRamp-49602]
	_ = x[OffRampNotSetForSelector-49603]
	_ = x[OffRampAddressMismatch-49604]
	_ = x[ErrorSubjectCursed-49605]
	_ = x[ErrorNotOnRamp-49606]
	_ = x[ErrorMissingTokenAmounts-49607]
	_ = x[ErrorNoMultiTokenTransfers-49608]
	_ = x[ErrorInsufficientFee-49609]
}

const _ExitCode_name = "ErrorDestChainNotEnabledErrorSourceChainNotEnabledSenderIsNotOffRampOffRampNotSetForSelectorOffRampAddressMismatchErrorSubjectCursedErrorNotOnRampErrorMissingTokenAmountsErrorNoMultiTokenTransfersErrorInsufficientFee"

var _ExitCode_index = [...]uint8{0, 24, 50, 68, 92, 114, 132, 146, 170, 196, 216}

func (i ExitCode) String() string {
	idx := int(i) - 49600
	if i < 49600 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
