// Code generated by "stringer -type=ExitCode -trimprefix=ExitCode -output=exitcode_string.go"; DO NOT EDIT.

package lockreleaselockbox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExitCodeLockboxNotConfigured-48700]
	_ = x[ExitCodeUnexpectedLockboxConfirmationSender-48701]
	_ = x[ExitCodeUnexpectedLockBounce-48702]
	_ = x[ExitCodeInvalidOffRampAccountReply-48703]
	_ = x[ExitCodeInvalidOffRampAccountNotification-48704]
	_ = x[ExitCodeOffRampAccountDeployFailed-48705]
	_ = x[ExitCodeLockboxWithdrawFailed-48706]
}

const _ExitCode_name = "LockboxNotConfiguredUnexpectedLockboxConfirmationSenderUnexpectedLockBounceInvalidOffRampAccountReplyInvalidOffRampAccountNotificationOffRampAccountDeployFailedLockboxWithdrawFailed"

var _ExitCode_index = [...]uint8{0, 20, 55, 75, 101, 134, 160, 181}

func (i ExitCode) String() string {
	idx := int(i) - 48700
	if i < 48700 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
