// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package ccipsendexecutor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorUnauthorized-265]
	_ = x[ErrorStateNotExpected-500]
	_ = x[InsufficientFee-43602]
}

const (
	_ExitCode_name_0 = "ErrorUnauthorized"
	_ExitCode_name_1 = "ErrorStateNotExpected"
	_ExitCode_name_2 = "InsufficientFee"
)

func (i ExitCode) String() string {
	switch {
	case i == 265:
		return _ExitCode_name_0
	case i == 500:
		return _ExitCode_name_1
	case i == 43602:
		return _ExitCode_name_2
	default:
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
