[package]
name = "@chainlink/contracts-ton"
description = "Chainlink TON smart contracts"
version = "1.6.2"
license = "see LICENSE in LICENSE"

[wrappers.typescript]
output-dir = "wrappers/gen"

[contracts.Router]
display-name = "link.chain.ton.ccip.Router"
src = "contracts/ccip/router/contract.tolk"
domain = "ccip"
depends = []

[contracts.OnRamp]
display-name = "link.chain.ton.ccip.OnRamp"
src = "contracts/ccip/onramp/contract.tolk"
domain = "ccip"
depends = []

[fmt]
width = 100
ignore = []

[import-mappings]
acton = ".acton"
