// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUnknownDestChainSelector-256]
	_ = x[DestChainNotEnabled-257]
	_ = x[FeeTokenNotSupported-258]
	_ = x[StaleGasPrice-259]
	_ = x[InvalidMsgData-260]
	_ = x[SenderNotAllowed-261]
	_ = x[InvalidMessageDestChainSelector-262]
	_ = x[SourceChainSelectorMismatch-263]
	_ = x[TokenNotSupported-264]
	_ = x[Unauthorized-265]
	_ = x[SourceChainNotEnabled-266]
	_ = x[EmptyReport-267]
	_ = x[DispatchNotFromMerkleRoot-268]
}

const _ExitCode_name = "ErrUnknownDestChainSelectorDestChainNotEnabledFeeTokenNotSupportedStaleGasPriceInvalidMsgDataSenderNotAllowedInvalidMessageDestChainSelectorSourceChainSelectorMismatchTokenNotSupportedUnauthorizedSourceChainNotEnabledEmptyReportDispatchNotFromMerkleRoot"

var _ExitCode_index = [...]uint8{0, 27, 46, 66, 79, 93, 109, 140, 167, 184, 196, 217, 228, 253}

func (i ExitCode) String() string {
	idx := int(i) - 256
	if i < 256 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
