// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorUnknownDestChainSelector-256]
	_ = x[ErrorDestChainNotEnabled-257]
	_ = x[ErrorFeeTokenNotSupported-258]
	_ = x[ErrorStaleGasPrice-259]
	_ = x[ErrorInvalidMsgData-260]
	_ = x[ErrorSenderNotAllowed-261]
	_ = x[ErrorInvalidMessageDestChainSelector-262]
	_ = x[ErrorSourceChainSelectorMismatch-263]
	_ = x[ErrorTokenNotSupported-264]
	_ = x[ErrorUnauthorized-265]
	_ = x[ErrorSourceChainNotEnabled-266]
	_ = x[ErrorEmptyReport-267]
	_ = x[ErrorDispatchNotFromMerkleRoot-268]
}

const _ExitCode_name = "ErrorUnknownDestChainSelectorErrorDestChainNotEnabledErrorFeeTokenNotSupportedErrorStaleGasPriceErrorInvalidMsgDataErrorSenderNotAllowedErrorInvalidMessageDestChainSelectorErrorSourceChainSelectorMismatchErrorTokenNotSupportedErrorUnauthorizedErrorSourceChainNotEnabledErrorEmptyReportErrorDispatchNotFromMerkleRoot"

var _ExitCode_index = [...]uint16{0, 29, 53, 78, 96, 115, 136, 172, 204, 226, 243, 269, 285, 315}

func (i ExitCode) String() string {
	idx := int(i) - 256
	if i < 256 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
