// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package jetton_withdrawable

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZeroAddressNotAllowed-55700]
	_ = x[UnallowedRecipient-55701]
	_ = x[MaxAmountExceeded-55702]
	_ = x[InsufficientValue-55703]
	_ = x[NonEmptyCustomPayload-55704]
}

const _ExitCode_name = "ZeroAddressNotAllowedUnallowedRecipientMaxAmountExceededInsufficientValueNonEmptyCustomPayload"

var _ExitCode_index = [...]uint8{0, 21, 39, 56, 73, 94}

func (i ExitCode) String() string {
	idx := int(i) - 55700
	if i < 55700 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
