// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package wallet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BalanceError-47]
	_ = x[NotEnoughGas-48]
	_ = x[InvalidMessage-49]
}

const _ExitCode_name = "BalanceErrorNotEnoughGasInvalidMessage"

var _ExitCode_index = [...]uint8{0, 12, 24, 38}

func (i ExitCode) String() string {
	idx := int(i) - 47
	if i < 47 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
