// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/smartcontractkit/chainlink-common/pkg/types/ccipocr3"
	mock "github.com/stretchr/testify/mock"
)

// NewChainSpecificAddressCodec creates a new instance of ChainSpecificAddressCodec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChainSpecificAddressCodec(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChainSpecificAddressCodec {
	mock := &ChainSpecificAddressCodec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChainSpecificAddressCodec is an autogenerated mock type for the ChainSpecificAddressCodec type
type ChainSpecificAddressCodec struct {
	mock.Mock
}

type ChainSpecificAddressCodec_Expecter struct {
	mock *mock.Mock
}

func (_m *ChainSpecificAddressCodec) EXPECT() *ChainSpecificAddressCodec_Expecter {
	return &ChainSpecificAddressCodec_Expecter{mock: &_m.Mock}
}

// AddressBytesToString provides a mock function for the type ChainSpecificAddressCodec
func (_mock *ChainSpecificAddressCodec) AddressBytesToString(bytes []byte) (string, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for AddressBytesToString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (string, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ChainSpecificAddressCodec_AddressBytesToString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddressBytesToString'
type ChainSpecificAddressCodec_AddressBytesToString_Call struct {
	*mock.Call
}

// AddressBytesToString is a helper method to define mock.On call
//   - bytes []byte
func (_e *ChainSpecificAddressCodec_Expecter) AddressBytesToString(bytes interface{}) *ChainSpecificAddressCodec_AddressBytesToString_Call {
	return &ChainSpecificAddressCodec_AddressBytesToString_Call{Call: _e.mock.On("AddressBytesToString", bytes)}
}

func (_c *ChainSpecificAddressCodec_AddressBytesToString_Call) Run(run func(bytes []byte)) *ChainSpecificAddressCodec_AddressBytesToString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChainSpecificAddressCodec_AddressBytesToString_Call) Return(s string, err error) *ChainSpecificAddressCodec_AddressBytesToString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ChainSpecificAddressCodec_AddressBytesToString_Call) RunAndReturn(run func(bytes []byte) (string, error)) *ChainSpecificAddressCodec_AddressBytesToString_Call {
	_c.Call.Return(run)
	return _c
}

// AddressStringToBytes provides a mock function for the type ChainSpecificAddressCodec
func (_mock *ChainSpecificAddressCodec) AddressStringToBytes(s string) ([]byte, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for AddressStringToBytes")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ChainSpecificAddressCodec_AddressStringToBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddressStringToBytes'
type ChainSpecificAddressCodec_AddressStringToBytes_Call struct {
	*mock.Call
}

// AddressStringToBytes is a helper method to define mock.On call
//   - s string
func (_e *ChainSpecificAddressCodec_Expecter) AddressStringToBytes(s interface{}) *ChainSpecificAddressCodec_AddressStringToBytes_Call {
	return &ChainSpecificAddressCodec_AddressStringToBytes_Call{Call: _e.mock.On("AddressStringToBytes", s)}
}

func (_c *ChainSpecificAddressCodec_AddressStringToBytes_Call) Run(run func(s string)) *ChainSpecificAddressCodec_AddressStringToBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChainSpecificAddressCodec_AddressStringToBytes_Call) Return(bytes []byte, err error) *ChainSpecificAddressCodec_AddressStringToBytes_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *ChainSpecificAddressCodec_AddressStringToBytes_Call) RunAndReturn(run func(s string) ([]byte, error)) *ChainSpecificAddressCodec_AddressStringToBytes_Call {
	_c.Call.Return(run)
	return _c
}

// OracleIDAsAddressBytes provides a mock function for the type ChainSpecificAddressCodec
func (_mock *ChainSpecificAddressCodec) OracleIDAsAddressBytes(oracleID uint8) ([]byte, error) {
	ret := _mock.Called(oracleID)

	if len(ret) == 0 {
		panic("no return value specified for OracleIDAsAddressBytes")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint8) ([]byte, error)); ok {
		return returnFunc(oracleID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint8) []byte); ok {
		r0 = returnFunc(oracleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint8) error); ok {
		r1 = returnFunc(oracleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ChainSpecificAddressCodec_OracleIDAsAddressBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OracleIDAsAddressBytes'
type ChainSpecificAddressCodec_OracleIDAsAddressBytes_Call struct {
	*mock.Call
}

// OracleIDAsAddressBytes is a helper method to define mock.On call
//   - oracleID uint8
func (_e *ChainSpecificAddressCodec_Expecter) OracleIDAsAddressBytes(oracleID interface{}) *ChainSpecificAddressCodec_OracleIDAsAddressBytes_Call {
	return &ChainSpecificAddressCodec_OracleIDAsAddressBytes_Call{Call: _e.mock.On("OracleIDAsAddressBytes", oracleID)}
}

func (_c *ChainSpecificAddressCodec_OracleIDAsAddressBytes_Call) Run(run func(oracleID uint8)) *ChainSpecificAddressCodec_OracleIDAsAddressBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint8
		if args[0] != nil {
			arg0 = args[0].(uint8)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChainSpecificAddressCodec_OracleIDAsAddressBytes_Call) Return(bytes []byte, err error) *ChainSpecificAddressCodec_OracleIDAsAddressBytes_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *ChainSpecificAddressCodec_OracleIDAsAddressBytes_Call) RunAndReturn(run func(oracleID uint8) ([]byte, error)) *ChainSpecificAddressCodec_OracleIDAsAddressBytes_Call {
	_c.Call.Return(run)
	return _c
}

// TransmitterBytesToString provides a mock function for the type ChainSpecificAddressCodec
func (_mock *ChainSpecificAddressCodec) TransmitterBytesToString(bytes []byte) (string, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for TransmitterBytesToString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (string, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ChainSpecificAddressCodec_TransmitterBytesToString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransmitterBytesToString'
type ChainSpecificAddressCodec_TransmitterBytesToString_Call struct {
	*mock.Call
}

// TransmitterBytesToString is a helper method to define mock.On call
//   - bytes []byte
func (_e *ChainSpecificAddressCodec_Expecter) TransmitterBytesToString(bytes interface{}) *ChainSpecificAddressCodec_TransmitterBytesToString_Call {
	return &ChainSpecificAddressCodec_TransmitterBytesToString_Call{Call: _e.mock.On("TransmitterBytesToString", bytes)}
}

func (_c *ChainSpecificAddressCodec_TransmitterBytesToString_Call) Run(run func(bytes []byte)) *ChainSpecificAddressCodec_TransmitterBytesToString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChainSpecificAddressCodec_TransmitterBytesToString_Call) Return(s string, err error) *ChainSpecificAddressCodec_TransmitterBytesToString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ChainSpecificAddressCodec_TransmitterBytesToString_Call) RunAndReturn(run func(bytes []byte) (string, error)) *ChainSpecificAddressCodec_TransmitterBytesToString_Call {
	_c.Call.Return(run)
	return _c
}

// NewSourceChainExtraDataCodec creates a new instance of SourceChainExtraDataCodec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSourceChainExtraDataCodec(t interface {
	mock.TestingT
	Cleanup(func())
}) *SourceChainExtraDataCodec {
	mock := &SourceChainExtraDataCodec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SourceChainExtraDataCodec is an autogenerated mock type for the SourceChainExtraDataCodec type
type SourceChainExtraDataCodec struct {
	mock.Mock
}

type SourceChainExtraDataCodec_Expecter struct {
	mock *mock.Mock
}

func (_m *SourceChainExtraDataCodec) EXPECT() *SourceChainExtraDataCodec_Expecter {
	return &SourceChainExtraDataCodec_Expecter{mock: &_m.Mock}
}

// DecodeDestExecDataToMap provides a mock function for the type SourceChainExtraDataCodec
func (_mock *SourceChainExtraDataCodec) DecodeDestExecDataToMap(destExecData ccipocr3.Bytes) (map[string]any, error) {
	ret := _mock.Called(destExecData)

	if len(ret) == 0 {
		panic("no return value specified for DecodeDestExecDataToMap")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ccipocr3.Bytes) (map[string]any, error)); ok {
		return returnFunc(destExecData)
	}
	if returnFunc, ok := ret.Get(0).(func(ccipocr3.Bytes) map[string]any); ok {
		r0 = returnFunc(destExecData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ccipocr3.Bytes) error); ok {
		r1 = returnFunc(destExecData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SourceChainExtraDataCodec_DecodeDestExecDataToMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeDestExecDataToMap'
type SourceChainExtraDataCodec_DecodeDestExecDataToMap_Call struct {
	*mock.Call
}

// DecodeDestExecDataToMap is a helper method to define mock.On call
//   - destExecData ccipocr3.Bytes
func (_e *SourceChainExtraDataCodec_Expecter) DecodeDestExecDataToMap(destExecData interface{}) *SourceChainExtraDataCodec_DecodeDestExecDataToMap_Call {
	return &SourceChainExtraDataCodec_DecodeDestExecDataToMap_Call{Call: _e.mock.On("DecodeDestExecDataToMap", destExecData)}
}

func (_c *SourceChainExtraDataCodec_DecodeDestExecDataToMap_Call) Run(run func(destExecData ccipocr3.Bytes)) *SourceChainExtraDataCodec_DecodeDestExecDataToMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ccipocr3.Bytes
		if args[0] != nil {
			arg0 = args[0].(ccipocr3.Bytes)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SourceChainExtraDataCodec_DecodeDestExecDataToMap_Call) Return(stringToV map[string]any, err error) *SourceChainExtraDataCodec_DecodeDestExecDataToMap_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *SourceChainExtraDataCodec_DecodeDestExecDataToMap_Call) RunAndReturn(run func(destExecData ccipocr3.Bytes) (map[string]any, error)) *SourceChainExtraDataCodec_DecodeDestExecDataToMap_Call {
	_c.Call.Return(run)
	return _c
}

// DecodeExtraArgsToMap provides a mock function for the type SourceChainExtraDataCodec
func (_mock *SourceChainExtraDataCodec) DecodeExtraArgsToMap(extraArgs ccipocr3.Bytes) (map[string]any, error) {
	ret := _mock.Called(extraArgs)

	if len(ret) == 0 {
		panic("no return value specified for DecodeExtraArgsToMap")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ccipocr3.Bytes) (map[string]any, error)); ok {
		return returnFunc(extraArgs)
	}
	if returnFunc, ok := ret.Get(0).(func(ccipocr3.Bytes) map[string]any); ok {
		r0 = returnFunc(extraArgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ccipocr3.Bytes) error); ok {
		r1 = returnFunc(extraArgs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SourceChainExtraDataCodec_DecodeExtraArgsToMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeExtraArgsToMap'
type SourceChainExtraDataCodec_DecodeExtraArgsToMap_Call struct {
	*mock.Call
}

// DecodeExtraArgsToMap is a helper method to define mock.On call
//   - extraArgs ccipocr3.Bytes
func (_e *SourceChainExtraDataCodec_Expecter) DecodeExtraArgsToMap(extraArgs interface{}) *SourceChainExtraDataCodec_DecodeExtraArgsToMap_Call {
	return &SourceChainExtraDataCodec_DecodeExtraArgsToMap_Call{Call: _e.mock.On("DecodeExtraArgsToMap", extraArgs)}
}

func (_c *SourceChainExtraDataCodec_DecodeExtraArgsToMap_Call) Run(run func(extraArgs ccipocr3.Bytes)) *SourceChainExtraDataCodec_DecodeExtraArgsToMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ccipocr3.Bytes
		if args[0] != nil {
			arg0 = args[0].(ccipocr3.Bytes)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SourceChainExtraDataCodec_DecodeExtraArgsToMap_Call) Return(stringToV map[string]any, err error) *SourceChainExtraDataCodec_DecodeExtraArgsToMap_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *SourceChainExtraDataCodec_DecodeExtraArgsToMap_Call) RunAndReturn(run func(extraArgs ccipocr3.Bytes) (map[string]any, error)) *SourceChainExtraDataCodec_DecodeExtraArgsToMap_Call {
	_c.Call.Return(run)
	return _c
}
