// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package ocr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorBigFMustBePositive-54500]
	_ = x[ErrorStaticConfigCannotBeChanged-54501]
	_ = x[ErrorTooManySigners-54502]
	_ = x[ErrorBigFTooHigh-54503]
	_ = x[ErrorTooManyTransmitters-54504]
	_ = x[ErrorNoTransmitters-54505]
	_ = x[ErrorRepeatedSigners-54506]
	_ = x[ErrorRepeatedTransmitters-54507]
	_ = x[ErrorConfigDigestMismatch-54508]
	_ = x[ErrorUnauthorizedTransmitter-54509]
	_ = x[ErrorWrongNumberOfSignatures-54510]
	_ = x[ErrorUnauthorizedSigner-54511]
	_ = x[ErrorNonUniqueSignatures-54512]
	_ = x[ErrorInvalidSignature-54513]
	_ = x[ErrorNonExistentOcrPluginType-54514]
	_ = x[ErrorNoSigners-54515]
}

const _ExitCode_name = "ErrorBigFMustBePositiveErrorStaticConfigCannotBeChangedErrorTooManySignersErrorBigFTooHighErrorTooManyTransmittersErrorNoTransmittersErrorRepeatedSignersErrorRepeatedTransmittersErrorConfigDigestMismatchErrorUnauthorizedTransmitterErrorWrongNumberOfSignaturesErrorUnauthorizedSignerErrorNonUniqueSignaturesErrorInvalidSignatureErrorNonExistentOcrPluginTypeErrorNoSigners"

var _ExitCode_index = [...]uint16{0, 23, 55, 74, 90, 114, 133, 153, 178, 203, 231, 259, 282, 306, 327, 356, 370}

func (i ExitCode) String() string {
	idx := int(i) - 54500
	if i < 54500 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
