// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package bindings

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorBelowOperationalBalance-70400]
}

const _ExitCode_name = "ErrorBelowOperationalBalance"

var _ExitCode_index = [...]uint8{0, 28}

func (i ExitCode) String() string {
	idx := int(i) - 70400
	if i < 70400 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
