package timelock

import (
	"encoding/hex"
	"math/big"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xssnick/tonutils-go/address"
	"github.com/xssnick/tonutils-go/tlb"
	"github.com/xssnick/tonutils-go/tvm/cell"

	"github.com/smartcontractkit/chainlink-ton/pkg/ccip/bindings/common"
	"github.com/smartcontractkit/chainlink-ton/pkg/ton/tlbe"
)

// Cross-implementation encoding tests for SnakedCell<Timelock_Call>.
//
// These tests verify that Go and TypeScript produce identical cell encodings.
// The expected hash values are generated from TypeScript and verified here in Go.
//
// ## How to regenerate expected hashes from TypeScript:
//
// 1. Run TypeScript tests:
//    cd contracts && npm test -- --testNamePattern="Cross-Implementation"
//
// 2. Update the expectedXxxHash constants below with the output.
//
// ## Test vector source:
//
// TypeScript tests: contracts/tests/mcms/SnakedCellEncoding.spec.ts
// Go tests: pkg/bindings/mcms/timelock/types_test.go (this file)

// Test addresses matching TypeScript tests
const (
	testAddress1 = "EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2"
	testAddress2 = "EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c"
)

// Expected hashes from TypeScript tests for cross-implementation verification.
// Generated by: cd contracts && npm test -- --testNamePattern="Cross-Implementation"
const (
	// Single Call: target=testAddress1, value=1 TON, data=0x12345678
	expectedCallHash = "9d76debffe8ed5a1aed0afc679a2184605e716d79eb0a620a26c816ffc4db69e"
	// SnakedCell<Call> with 2 calls
	expectedSnakedCellHash = "bdd17632e37830a1717d09be997fe13368b668f781406e2eaa3299e13da9d294"
	// OperationBatch with calls + predecessor=0 + salt=123456789
	expectedOperationBatchHash = "9425b1429118466b66ca668b982b36b99ca5a17cfe334002d1cd0728e4009320"
)

// buildTestCalls creates the two-call test vector used in SnakedCell and OperationBatch tests
func buildTestCalls(t *testing.T) common.SnakedCell[Call] {
	t.Helper()

	addr1, err := address.ParseAddr(testAddress1)
	require.NoError(t, err)
	addr2, err := address.ParseAddr(testAddress2)
	require.NoError(t, err)

	// Call 0: opcode 0x11111111, queryId 1, value 0.1 TON
	data0 := cell.BeginCell().MustStoreUInt(0x11111111, 32).MustStoreUInt(1, 64).EndCell()
	// Call 1: opcode 0x22222222, queryId 2, value 0.2 TON
	data1 := cell.BeginCell().MustStoreUInt(0x22222222, 32).MustStoreUInt(2, 64).EndCell()

	return common.SnakedCell[Call]{
		{Target: addr1, Value: tlb.FromNanoTON(big.NewInt(100000000)), Data: data0},
		{Target: addr2, Value: tlb.FromNanoTON(big.NewInt(200000000)), Data: data1},
	}
}

func TestCrossImplementationEncoding(t *testing.T) {
	t.Run("Call", func(t *testing.T) {
		addr1, err := address.ParseAddr(testAddress1)
		require.NoError(t, err)

		call := Call{
			Target: addr1,
			Value:  tlb.FromNanoTON(big.NewInt(1000000000)), // 1 TON
			Data:   cell.BeginCell().MustStoreUInt(0x12345678, 32).EndCell(),
		}

		encoded, err := tlb.ToCell(call)
		require.NoError(t, err)

		expectedHash, err := hex.DecodeString(expectedCallHash)
		require.NoError(t, err)
		require.Equal(t, expectedHash, encoded.Hash(), "Call encoding should match TypeScript")
	})

	t.Run("SnakedCell[Call]", func(t *testing.T) {
		calls := buildTestCalls(t)

		encoded, err := tlb.ToCell(calls)
		require.NoError(t, err)

		expectedHash, err := hex.DecodeString(expectedSnakedCellHash)
		require.NoError(t, err)
		require.Equal(t, expectedHash, encoded.Hash(), "SnakedCell<Call> encoding should match TypeScript")
	})

	t.Run("OperationBatch", func(t *testing.T) {
		opBatch := OperationBatch{
			Calls:       buildTestCalls(t),
			Predecessor: tlbe.NewUint256(big.NewInt(0)),
			Salt:        tlbe.NewUint256(big.NewInt(123456789)),
		}

		encoded, err := tlb.ToCell(opBatch)
		require.NoError(t, err)

		expectedHash, err := hex.DecodeString(expectedOperationBatchHash)
		require.NoError(t, err)
		require.Equal(t, expectedHash, encoded.Hash(), "OperationBatch encoding should match TypeScript")
	})
}
