// Code generated by "stringer -type=ExitCode -trimprefix=ExitCode -output=exitcode_string.go"; DO NOT EDIT.

package lockrelease

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExitCodePendingReleaseAlreadyExists-26300]
	_ = x[ExitCodePendingReleaseNotFound-26301]
	_ = x[ExitCodeUnexpectedReleaseConfirmationSender-26302]
	_ = x[ExitCodeUnexpectedReleaseBounce-26303]
}

const _ExitCode_name = "PendingReleaseAlreadyExistsPendingReleaseNotFoundUnexpectedReleaseConfirmationSenderUnexpectedReleaseBounce"

var _ExitCode_index = [...]uint8{0, 27, 49, 84, 107}

func (i ExitCode) String() string {
	idx := int(i) - 26300
	if i < 26300 || idx >= len(_ExitCode_index)-1 {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[idx]:_ExitCode_index[idx+1]]
}
