name: Build And Cache MyLocalTon Images

on:
  push:
    branches:
      - feature/CTF-GHA-cache
  workflow_dispatch:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout MyLocalTon Docker
        uses: actions/checkout@v4
        with:
          repository: neodix42/mylocalton-docker
          path: mylocalton-docker
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore Docker build cache
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: tmp/docker-cache
          key: docker-cache-${{ runner.os }}-${{ hashFiles('mylocalton-docker/docker-compose-build.yaml') }}
          restore-keys: docker-cache-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bake & load with local cache
        uses: docker/bake-action@v6
        with:
          source: .
          files: |
            mylocalton-docker/docker-compose-build.yaml
            .github/docker-cache.json
          load: true

      - name: Bring up MyLocalTon
        run: docker compose -f mylocalton-docker/docker-compose-build.yaml up -d

      - name: Run CTF integration tests
        run: |
          pushd integration-tests/examples
          CTF_CONFIGS=smoke_ton.toml go test -v -run TestTonSmoke

      - name: Save Docker build cache
        if: always()
        uses: actions/cache@v4
        with:
          path: tmp/docker-cache
          key: docker-cache-${{ runner.os }}-${{ hashFiles('tmp/docker-cache/**') }}
