name: TON - Contracts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build & Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run build
        run: |
          pushd contracts
          nix develop .#contracts -c yarn && yarn build

      - name: Run tests
        run: |
          pushd contracts
          nix develop .#contracts -c yarn test
  
      - name: Setup TON Localnet
        id: setup-ton-localnet
        uses: ./.github/actions/setup-ton-localnet
        with:
          repository: ${{ github.repository }}
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: nix develop . -c go test ./contracts/tests/... 

  build-nixpkg:
    name: Build nix package
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run build
        run: nix build -v .#contracts
