name: TON - Contracts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-check:
    name: Build & Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Deploy MyLocalTON (background)
        run: |
          pushd mylocalton
          docker compose up -d

      - name: Run build
        run: |
          pushd contracts
          nix develop .#contracts -c yarn && yarn build

      - name: Run TypeScript tests
        run: |
          pushd contracts
          nix develop .#contracts -c yarn test

      - name: Wait for MyLocalTON to be ready
        run: |
          echo "Waiting for MyLocalTON to be ready..."
          timeout 300 bash -c 'until curl -s http://localhost:8080/last; do sleep 5; done'

      - name: Run Go tests
        run: |
          cp pkg/tonutils/.env.example pkg/tonutils/.env
          pushd pkg/tonutils/tests/async_communication
          nix develop .#contracts -c go test -v -timeout 30m

  build-nixpkg:
    name: Build nix package
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run build
        run: nix build -v .#contracts
