name: TON - Relayer - Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  build-publish-docker:
    name: Build & Publish Docker Image
    permissions:
      contents: read
      id-token: write
    # TODO: replace with main branch ref, https://github.com/smartcontractkit/.github/pull/1025
    uses: smartcontractkit/.github/.github/workflows/reusable-docker-build-publish.yml@310d49c9ec745392820197b0f89b5023cc4e4156 # 2025-05-13
    with:
      # Internal dev ECR, retention policy based on tag
      aws-ecr-name: chainlink-plugins-dev
      aws-region-ecr: us-west-2
      aws-region-gati: us-west-2
      dockerfile: scripts/build/Dockerfile.build.nix
      docker-build-context: .
      docker-build-args: |
        CHAINLINK_USER=chainlink
        COMMIT_SHA=${{ github.sha }}
      docker-build-cache-disabled: "true"
      docker-manifest-sign: true
      docker-registry-url-override: public.ecr.aws/chainlink
      docker-tag-custom-suffix: "-chainlink-ton"
      git-sha: ${{ github.sha }}
      github-event-name: ${{ github.event_name }}
      github-ref-name: ${{ github.ref_name }}
      github-ref-type: ${{ github.ref_type }}
      github-workflow-repository: ${{ github.repository }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_SDLC }}
      AWS_ROLE_PUBLISH_ARN: ${{ secrets.AWS_OIDC_IAM_ROLE_SDLC_BUILD_PUBLISH_ARN }}
      AWS_ROLE_GATI_ARN: ${{ secrets.AWS_ROLE_ARN_GATI_READONLY }}
      AWS_LAMBDA_GATI_URL: ${{ secrets.AWS_LAMBDA_URL_GATI }}
