name: TON - Build Relayer Package

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build-check:
    name: Build & Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run build
        run: nix develop -c go build -v ./...

      - name: Run unit tests
        run: nix develop -c go test -v -count=1 -p=1 -timeout 30m ./...

  build-pkgs:
    name: Build and package (Nix and Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run build - Nix
        run: nix build -v .#chainlink-ton

      - name: Run build - Docker (via host)
        run: nix develop -c ./scripts/build/make-docker.sh

      - name: Run build - Docker (via Docker builder)
        run: nix develop -c ./scripts/build/make-docker.sh --docker-builder

  detect-tracetracking-changes:
    name: Detect changes on tracetracking package
    runs-on: ubuntu-latest
    outputs:
      tracetracking: ${{ steps.filter.outputs.tracetracking }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            tracetracking:
              - 'pkg/ton/tracetracking/**'
              - 'integration-tests/tracetracking/**'

  tracetracking-tests:
    name: Run tracetracking integration tests
    needs: detect-tracetracking-changes
    runs-on: ubuntu-latest
    if: needs.detect-tracetracking-changes.outputs.tracetracking == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build contracts
        run: |
          pushd contracts
          nix develop .#contracts -c yarn && yarn build
      - name: Run tracetracking tests
        run: |
          pushd integration-tests
          nix develop -c go test -v -count=1 -p=1 -timeout 30m -tags=tracetracking ./tracetracking
