name: TON - Relayer - Publish Docker Image PoC

on:
  push:
    branches:
      - chores-release-process
  pull_request:
    types: [labeled, opened, synchronize, reopened]  # Trigger when a label is added
  workflow_dispatch: # Manual trigger from GitHub UI

env:
  CHAINLINK_PUBLIC_ECR_IMAGE: public.ecr.aws/chainlink/chainlink
  

jobs:
  build-or-get-core:
    name: Build or Get Chainlink Core Base Image
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_CACHE_KEY_PREFIX: ccip-chainlink-core-cache-v1
      DOCKER_CACHE_DIR: ${{ github.workspace }}/.cache
      DOCKER_CACHE_TAR_NAME_SUFFIX: ccip-chainlink-core-cache.tar
    # outputs:
    #   date: ${{ steps.**.outputs.** }}
    steps:
      - name: Prepare Cache Dir
        run: mkdir -p ${{ env.DOCKER_CACHE_DIR }}

      - name: Setup GitHub token using GATI
        id: set-token
        uses: smartcontractkit/.github/actions/setup-github-token@setup-github-token/1.0.0
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN_GATI_READONLY }}
          aws-lambda-url: ${{ secrets.AWS_LAMBDA_URL_GATI }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-role-duration-seconds: "1800"

      - name: Checkout chainlink-ton Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Read Chainlink Core Ref from .core_version File
        id: read_core_ref
        run: echo "CORE_REF=$(cat ./scripts/.core_version | tr -d '[:space:]')" >> $GITHUB_OUTPUT

      - name: Detect if CORE_REF is a SHA
        id: detect_core_ref_is_sha
        run: |
          REF="${{ steps.read_core_ref.outputs.CORE_REF }}"
          if [[ "$REF" =~ ^[0-9a-fA-F]{7,40}$ ]]; then
            echo "is_sha=true" >> $GITHUB_OUTPUT
          else
            echo "is_sha=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Determine Base Image Name
        id: determine-base-image
        run: |
          if [[ "${{ steps.detect_core_ref_is_sha.outputs.is_sha }}" == "true" ]]; then
            echo "BASE_IMAGE=local_chainlink:${{ steps.read_core_ref.outputs.CORE_REF }}" >> $GITHUB_OUTPUT
          else
            echo "BASE_IMAGE=${{ env.CHAINLINK_PUBLIC_ECR_IMAGE }}:${{ steps.read_core_ref.outputs.CORE_REF }}" >> $GITHUB_OUTPUT
          fi

      - name: Debug
        id: debug
        run: |
          docker images

      - name: Restore Docker Images from Cache
        id: restore-cache-images
        uses: actions/cache@v4
        with:
          path: ${{ env.DOCKER_CACHE_DIR }}/${{ steps.read_core_ref.outputs.CORE_REF }}-${{ env.DOCKER_CACHE_TAR_NAME_SUFFIX }}
          key: ${{ env.DOCKER_CACHE_KEY_PREFIX }}-${{ steps.read_core_ref.outputs.CORE_REF }}
  
      - name: Debug
        id: debug-2
        run: |
          docker images

      - name: Pull & Save Image on Cache Miss When Core Ref Is Not a SHA
        if: steps.detect_core_ref_is_sha.outputs.is_sha == 'false' && steps.restore-cache-images.outputs.cache-hit != 'true'
        run: |
          echo "Cache Miss: Pulling chainlink core image from ${{ steps.determine-base-image.outputs.BASE_IMAGE }}"
          docker pull ${{ steps.determine-base-image.outputs.BASE_IMAGE }}

          echo "Saving to tarball…"
          docker save ${{ steps.determine-base-image.outputs.BASE_IMAGE }} \
            -o ${{ env.DOCKER_CACHE_DIR }}/${{ steps.read_core_ref.outputs.CORE_REF }}-${{ env.DOCKER_CACHE_TAR_NAME_SUFFIX }}

      - name: Check if Base Image Exists Locally When Core Ref Is a SHA
        if: steps.detect_core_ref_is_sha.outputs.is_sha == 'true'
        id: check-if-image-is-available
        run: |
          if docker image inspect ${{ steps.determine-base-image.outputs.BASE_IMAGE }} > /dev/null 2>&1; then
            echo "Cache Hit: Using existing image ${{ steps.determine-base-image.outputs.BASE_IMAGE }}"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Cache Miss: ${{ steps.determine-base-image.outputs.BASE_IMAGE }} not found locally. Proceed with building locally step."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Chainlink Core repo
        if: steps.detect_core_ref_is_sha.outputs.is_sha == 'true' && steps.check-if-image-is-available.outputs.exists == 'false'
        id: checkout-core
        uses: actions/checkout@v4
        with:
          repository: smartcontractkit/chainlink
          ref: ${{ steps.read_core_ref.outputs.CORE_REF }}
          path: temp/chainlink

      - name: Build Chainlink Image
        if: steps.detect_core_ref_is_sha.outputs.is_sha == 'true' && steps.check-if-image-is-available.outputs.exists == 'false'
        id: build-core
        env:
          GIT_AUTH_TOKEN: ${{ steps.set-token.outputs.access-token }}
        run: |
          cd temp/chainlink

          echo "🔎 Building from commit: $(git rev-parse HEAD)"
          echo "🔎 Commit message: $(git log -1 --pretty=%B)"
          echo "🔎 Branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "🔎 Dockerfile: plugins/chainlink.Dockerfile"
          echo "🔎 Build context: $(pwd)"

          docker buildx build \
            --secret id=GIT_AUTH_TOKEN \
            --build-arg COMMIT_SHA=$(git rev-parse HEAD) \
            -t ${{ steps.determine-base-image.outputs.BASE_IMAGE }} \
            -f plugins/chainlink.Dockerfile .

      - name: Debug
        id: debug-3
        run: |
          docker images

      - name: Save the Core Image Just Built
        if: steps.detect_core_ref_is_sha.outputs.is_sha == 'true' && steps.check-if-image-is-available.outputs.exists == 'false'
        run: |
          echo "Saving to tarball…"
          docker save ${{ steps.determine-base-image.outputs.BASE_IMAGE }} \
            -o ${{ env.DOCKER_CACHE_DIR }}/${{ steps.read_core_ref.outputs.CORE_REF }}-${{ env.DOCKER_CACHE_TAR_NAME_SUFFIX }}
      

  # build-publish-docker:
  #   name: Build & Publish Docker Image
  #   if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'build-publish-docker') }}
  #   permissions:
  #     contents: read
  #     id-token: write
  #   uses: smartcontractkit/.github/.github/workflows/reusable-docker-build-publish.yml@317784689643295083653d9c9d08d34d8e379a7f # 2025-05-13
  #   with:
  #     # Internal dev ECR, retention policy based on tag
  #     aws-ecr-name: chainlink-plugins-dev
  #     aws-region-ecr: ${{ vars.AWS_REGION }}
  #     aws-region-gati: ${{ vars.AWS_REGION }}
  #     dockerfile: scripts/build/Dockerfile.build.nix
  #     docker-build-context: .
  #     docker-build-args: |
  #       CHAINLINK_USER=chainlink
  #       COMMIT_SHA=${{ github.sha }}
  #       BASE_IMAGE=$${{ steps.determine-base-image.outputs.BASE_IMAGE }}
  #     docker-manifest-sign: true
  #     docker-tag-custom-suffix: "-chainlink-ton"
  #     git-sha: ${{ github.sha }}
  #     github-event-name: ${{ github.event_name }}
  #     github-ref-name: ${{ github.ref_name }}
  #     github-ref-type: ${{ github.ref_type }}
  #     github-workflow-repository: ${{ github.repository }}
  #   secrets:
  #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_STAGING }}
  #     AWS_ROLE_PUBLISH_ARN: ${{ secrets.AWS_ROLE_PUBLISH_ARN_STAGING }}
  #     AWS_ROLE_GATI_ARN: ${{ secrets.AWS_ROLE_ARN_GATI_READONLY }}
  #     AWS_LAMBDA_GATI_URL: ${{ secrets.AWS_LAMBDA_URL_GATI }}
