name: Temp MyLocalTON Test - Prebuilt Images

on:
  push:
    branches:
      - feature/mylocalton
  pull_request:
  workflow_dispatch:
    inputs:
      disable_volume_cache:
        description: 'Disable volume caching'
        type: boolean
        default: false
      disable_image_cache:
        description: 'Disable Docker image caching'
        type: boolean
        default: false

jobs:
  test-localnet:
    name: Testing MyLocalTON
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker volumes
        id: cache-volumes
        if: ${{ !github.event.inputs.disable_volume_cache || github.event.inputs.disable_volume_cache != 'true' }}
        uses: actions/cache@v4
        with:
          path: ~/.ton-volumes
          key: ${{ runner.os }}-ton-volumes-${{ hashFiles('docker-compose.yaml') }}
          restore-keys: |
            ${{ runner.os }}-ton-volumes-

      - name: Prepare cache directory and set env vars
        run: |
          mkdir -p ~/.ton-volumes

          if [ "${{ steps.cache-volumes.outputs.cache-hit }}" == "true" ] && [ "${{ github.event.inputs.disable_volume_cache }}" != "true" ]; then
            echo "Using cached volumes from previous run"
            mkdir -p ~/.ton-volumes/{shared-data,ton-db,postgres-data,index-workdir}
            echo "VOLUME_DRIVER=local" >> $GITHUB_ENV
            echo "SHARED_DATA_O_OPT=bind" >> $GITHUB_ENV
            echo "SHARED_DATA_TYPE_OPT=none" >> $GITHUB_ENV
            echo "SHARED_DATA_DEVICE_OPT=$HOME/.ton-volumes/shared-data" >> $GITHUB_ENV
            echo "TON_DB_O_OPT=bind" >> $GITHUB_ENV
            echo "TON_DB_TYPE_OPT=none" >> $GITHUB_ENV
            echo "TON_DB_DEVICE_OPT=$HOME/.ton-volumes/ton-db" >> $GITHUB_ENV
            echo "POSTGRES_DATA_O_OPT=bind" >> $GITHUB_ENV
            echo "POSTGRES_DATA_TYPE_OPT=none" >> $GITHUB_ENV
            echo "POSTGRES_DATA_DEVICE_OPT=$HOME/.ton-volumes/postgres-data" >> $GITHUB_ENV
            echo "INDEX_WORKDIR_O_OPT=bind" >> $GITHUB_ENV
            echo "INDEX_WORKDIR_TYPE_OPT=none" >> $GITHUB_ENV
            echo "INDEX_WORKDIR_DEVICE_OPT=$HOME/.ton-volumes/index-workdir" >> $GITHUB_ENV
            echo "COMPOSE_PROJECT_NAME=mylocalton" >> $GITHUB_ENV
            export COMPOSE_PROJECT_NAME=mylocalton
          else
            echo "Volume cache disabled or first run - will use default volumes"
          fi

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Mirror prebuilt images with skopeo
        run: |
          TARGET_REGISTRY="ghcr.io/${{ github.repository }}"
          IMAGES=(
            "ghcr.io/neodix42/mylocalton-docker:latest"
            "ghcr.io/neodix42/ton-http-api:latest"
            "ghcr.io/neodix42/mylocalton-docker-faucet:latest"
            "redis:latest"
            "postgres:17"
            "toncenter/ton-indexer-classifier:v1.2.0-test"
            "toncenter/ton-indexer-api:v1.2.0-test"
            "toncenter/ton-indexer-worker:v1.2.0-test"
          )

          echo "Starting parallel skopeo mirror…"
          pids=()

          for IMG in "${IMAGES[@]}"; do
            (
              NAME=$(basename "${IMG%%:*}")
              TAG="${IMG##*:}"
              SRC="docker://${IMG}"
              DST="docker://${TARGET_REGISTRY}/mylocalton-${NAME}:${TAG}"

              # check if the image is already in our registry (if caching is enabled)
              if [ "${{ github.event.inputs.disable_image_cache }}" != "true" ] && skopeo inspect "$DST" &>/dev/null; then
                echo "✓ [$] Image already cached in registry: ${DST}"
              else
                echo "→ [$] Mirroring $IMG → ${DST}"
                skopeo copy --all --retry-times=3 "$SRC" "$DST"
                echo "✓ [$] Mirrored to registry: ${DST}"
              fi

              echo "→ [$$] Pulling ${DST} locally"
              docker pull "${TARGET_REGISTRY}/mylocalton-${NAME}:${TAG}"
              
              # Tag with the original name so docker-compose can find it
              echo "→ [$$] Tagging as original: ${IMG}"
              docker tag "${TARGET_REGISTRY}/mylocalton-${NAME}:${TAG}" "${IMG}"
              
              echo "✔ [$$] Processed ${NAME}:${TAG}"
            ) &
            pids+=($!)
          done

          echo "Waiting for all mirrors to complete…"
          for pid in "${pids[@]}"; do
            wait "$pid"
          done

          echo "All images mirrored and tagged with original names."
          echo "Listing available images:"
          docker images

      - name: Start TON Local Network
        id: ton-startup
        run: |
          chmod +x scripts/localnet/localnet-up.sh
          scripts/localnet/localnet-up.sh

          if [ "${{ steps.cache-volumes.outputs.cache-hit }}" != "true" ] && [ "${{ github.event.inputs.disable_volume_cache }}" != "true" ]; then
            echo "Caching volumes for future runs"
            mkdir -p ~/.ton-volumes/{shared-data,ton-db,postgres-data,index-workdir}
            docker cp genesis:/usr/share/data/. ~/.ton-volumes/shared-data/
            docker cp genesis:/var/ton-work/db/. ~/.ton-volumes/ton-db/
            docker cp index-postgres:/var/lib/postgresql/data/. ~/.ton-volumes/postgres-data/
            docker cp index-worker:/workdir/. ~/.ton-volumes/index-workdir/
            chmod -R 777 ~/.ton-volumes
          fi

      - name: Run build
        run: |
          pushd contracts
          nix develop .#contracts -c yarn && yarn build

      - name: Run tests
        run: |
          pushd contracts
          nix develop .#contracts -c yarn test

      - name: Timestamp and Summary
        run: |
          echo "Job completed at $(date)"
          echo "Summary of cache settings:"
          echo "- Volume caching: ${{ github.event.inputs.disable_volume_cache == 'true' && 'DISABLED' || 'ENABLED' }}"
          echo "- Image caching: ${{ github.event.inputs.disable_image_cache == 'true' && 'DISABLED' || 'ENABLED' }}"