name: TON - Contracts

on:
  push:
    branches:
      - feature/mylocalton
  pull_request:

jobs:
  test-localnet:
    name: Testing MyLocalTON
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install Nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Start TON Local Network
        run: |
          chmod +x scripts/localnet-up.sh
          scripts/localnet-up.sh

      - name: Run tests
        run: |
          pushd contracts
          nix develop .#contracts -c yarn test
