name: TON - CTF Testing

on:
  push:
    branches:
      - feature/CTF-GHA-cache
  pull_request:

jobs:
  ctf-test:
    name: Build & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup MyLocalTon images
        uses: ./github/actions/mylocalton-images

      - name: Setup Go
        uses: smartcontractkit/.github/actions/setup-golang@setup-golang/v1
        with:
          go-version-file: integration-tests/go.mod
          use-go-cache: true

      - name: Run tests
        run: |
          pushd integration-tests/examples
          CTF_CONFIGS=smoke_ton.toml go test -v -run TestTonSmoke
