name: Run TON Smoke Tests

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
    - cron: '0 3 * * *'       # runs each night at 03:00 UTC

jobs:
  get_chainlink_version:
    name: Get Chainlink Version
    runs-on: ubuntu-24.04
    outputs:
      chainlink_version: ${{ steps.get-version.outputs.chainlink_version }}
    steps:
    - name: Set Chainlink version
      id: get-version
      run: |
        # Default to the pinned version for PRs
        CHAINLINK_VERSION="80e09da8e48b1d52534530a7882dffffae0858db" # Dec 30, 2025

        # If this is a scheduled (nightly) run, switch to develop
        if [[ "${{ github.event_name }}" == "schedule" ]]; then
            CHAINLINK_VERSION="develop"
        fi

        echo "chainlink_version=$CHAINLINK_VERSION" >> "$GITHUB_OUTPUT"
  run-ton-smoke-tests:
    name: Run TON Smoke Tests in Chainlink CCIP
    uses: smartcontractkit/chainlink-ccip/.github/workflows/test_smoke.yml@tt/ton
    needs: [get_chainlink_version]
    with:
      ton_ref: ${{ github.head_ref || github.sha }}
      chainlink_version: ${{ needs.get_chainlink_version.outputs.chainlink_version }}
      contract_version: 99dca5448b92 #todo: allow to use local
      custom_config: env.toml,env-cl-rebuild-ci.toml,../chainlink-ton/devenv-impl/ton.toml
