name: TON - CTF Testing - Manual Local Caching Images

on:
  push:
    branches:
      - feature/CTF-GHA-cache
  pull_request:

jobs:
  ctf-test:
    name: Build & Integration Tests
    runs-on: ubuntu-latest
    env:
      CACHE_DIR: integration-tests/.cache/images
      TON_IMAGES: >-
        ghcr.io/neodix42/mylocalton-docker:latest
        redis:latest
        postgres:17
        ghcr.io/neodix42/ton-http-api:latest
        ghcr.io/neodix42/mylocalton-docker-faucet:latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Prepare cache directory
        run: mkdir -p ${{ env.CACHE_DIR }}

      - name: Retrieve cached Docker images
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}/docker-images.tar
          key: mylocalton-images-v1

      - name: Pull Docker images (if no cache hit)
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss - pulling Docker images"
          for image in ${{ env.TON_IMAGES }}; do
            echo "Pulling $image"
            docker pull $image
          done
          echo "Saving Docker images to cache"
          docker save ${{ env.TON_IMAGES }} -o ${{ env.CACHE_DIR }}/docker-images.tar

      - name: Load cached Docker images
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: |
          echo "Cache hit - loading Docker images"
          docker load -i ${{ env.CACHE_DIR }}/docker-images.tar

      - name: Install Nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run tests
        run: |
          pushd integration-tests/examples
          nix develop -c env CTF_CONFIGS=smoke_ton.toml go test -v -run TestTonSmoke